### ISSUE TITLE
'use strict' & dropCache()

### ISSUE THREAD

**Issue by ihorskyi** [immutables/highlands#2]
Forgot to tell yesterday that `buck.js` was the only file where I could not add `'use strict'` because it immediately breaks the runtime (which is correct behavior in this case). The reason is `cachedTargets` is not defined (_and also no used anywhere else as cache or something_). 

https://github.com/immutables/highlands/blob/d6885f08cf322e779766fcb4830735f0bffd8c02/buck.js#L153-L157

**Comment by elucash** [comment]
should it be `cachedInfo = {}` in `dropCache` maybe it's copy-paste-rename issue

**Comment by elucash** [comment]
fixed in 5a775cd340ba13825152a21adab73e9a2b77eeff
tnx!
